"""Initial migration

Revision ID: de56b4a932d7
Revises: 
Create Date: 2025-06-01 11:32:10.625382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de56b4a932d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nichos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('id_nicho', sa.Integer(), nullable=False),
    sa.Column('perfil_cliente', sa.String(length=255), nullable=False),
    sa.Column('cluster', sa.String(length=255), nullable=False),
    sa.Column('prompt_path', sa.String(length=255), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_nicho'], ['nichos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execucoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('palavras_chave', sa.Text(), nullable=False),
    sa.Column('cluster_usado', sa.String(length=255), nullable=False),
    sa.Column('prompt_usado', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_execucao', sa.DateTime(), nullable=False),
    sa.Column('tempo_estimado', sa.Float(), nullable=True),
    sa.Column('tempo_real', sa.Float(), nullable=True),
    sa.Column('log_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execucoes')
    op.drop_table('categorias')
    op.drop_table('nichos')
    # ### end Alembic commands ###
