"""Refactor models to Flask-SQLAlchemy

Revision ID: ff9e42cc1fd4
Revises: de56b4a932d7
Create Date: 2025-06-01 11:55:51.506574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9e42cc1fd4'
down_revision: Union[str, None] = 'de56b4a932d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_operacao', sa.String(length=50), nullable=False),
    sa.Column('entidade', sa.String(length=50), nullable=False),
    sa.Column('id_referencia', sa.Integer(), nullable=True),
    sa.Column('usuario', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    # ### end Alembic commands ###
