# Configuração de Feature Flags - IMP-014
# Tracing ID: IMP014_FEATURE_FLAGS_001_20241227
# Data: 2024-12-27

features:
  # Feature: Nova Interface do Usuário
  - name: "new_ui"
    description: "Nova interface do usuário com design moderno"
    feature_type: "boolean"
    enabled: false
    rollout_strategy: "all_or_nothing"
    created_by: "product_team"
    metadata:
      category: "ui"
      priority: "high"
      jira_ticket: "UI-123"

  # Feature: Analytics Avançados
  - name: "advanced_analytics"
    description: "Sistema de analytics avançados com métricas detalhadas"
    feature_type: "percentage"
    enabled: true
    rollout_strategy: "percentage"
    rollout_percentage: 25.0
    created_by: "data_team"
    metadata:
      category: "analytics"
      priority: "medium"
      jira_ticket: "ANALYTICS-456"

  # Feature: Recursos Beta
  - name: "beta_features"
    description: "Recursos em fase beta para usuários selecionados"
    feature_type: "targeted"
    enabled: true
    rollout_strategy: "targeted_users"
    target_users:
      - "admin"
      - "beta_tester"
      - "power_user"
    created_by: "dev_team"
    metadata:
      category: "beta"
      priority: "low"
      jira_ticket: "BETA-789"

  # Feature: Integração com IA
  - name: "ai_integration"
    description: "Integração com sistema de IA para sugestões inteligentes"
    feature_type: "gradual"
    enabled: true
    rollout_strategy: "gradual"
    rollout_percentage: 50.0
    start_date: "2024-12-01T00:00:00"
    created_by: "ai_team"
    metadata:
      category: "ai"
      priority: "high"
      jira_ticket: "AI-101"

  # Feature: Pagamentos Avançados
  - name: "advanced_payments"
    description: "Sistema de pagamentos avançados com múltiplas formas"
    feature_type: "targeted"
    enabled: false
    rollout_strategy: "targeted_environments"
    target_environments:
      - "staging"
      - "production"
    created_by: "payment_team"
    metadata:
      category: "payments"
      priority: "critical"
      jira_ticket: "PAY-202"

  # Feature: Cache Inteligente
  - name: "smart_cache"
    description: "Sistema de cache inteligente com invalidação automática"
    feature_type: "boolean"
    enabled: true
    rollout_strategy: "all_or_nothing"
    created_by: "infrastructure_team"
    metadata:
      category: "performance"
      priority: "high"
      jira_ticket: "PERF-303"

  # Feature: Notificações Push
  - name: "push_notifications"
    description: "Sistema de notificações push em tempo real"
    feature_type: "percentage"
    enabled: true
    rollout_strategy: "percentage"
    rollout_percentage: 10.0
    created_by: "mobile_team"
    metadata:
      category: "notifications"
      priority: "medium"
      jira_ticket: "MOBILE-404"

  # Feature: Relatórios Avançados
  - name: "advanced_reports"
    description: "Relatórios avançados com exportação personalizada"
    feature_type: "targeted"
    enabled: false
    rollout_strategy: "targeted_users"
    target_users:
      - "admin"
      - "manager"
    created_by: "reports_team"
    metadata:
      category: "reports"
      priority: "medium"
      jira_ticket: "REPORTS-505"

  # Feature: Gamificação
  - name: "gamification"
    description: "Sistema de gamificação com pontos e conquistas"
    feature_type: "time_based"
    enabled: true
    rollout_strategy: "gradual"
    rollout_percentage: 75.0
    start_date: "2024-12-15T00:00:00"
    end_date: "2025-01-15T00:00:00"
    created_by: "ux_team"
    metadata:
      category: "engagement"
      priority: "low"
      jira_ticket: "UX-606"

  # Feature: Backup Automático
  - name: "auto_backup"
    description: "Sistema de backup automático com retenção configurável"
    feature_type: "boolean"
    enabled: true
    rollout_strategy: "all_or_nothing"
    created_by: "devops_team"
    metadata:
      category: "security"
      priority: "critical"
      jira_ticket: "SEC-707"

# Configurações globais
global_settings:
  cache_ttl_seconds: 300
  enable_audit: true
  redis_url: "redis://localhost:6379/0"
  log_level: "INFO"

# Configurações por ambiente
environments:
  development:
    default_enabled: true
    cache_ttl_seconds: 60
    enable_audit: true
  
  staging:
    default_enabled: false
    cache_ttl_seconds: 180
    enable_audit: true
  
  production:
    default_enabled: false
    cache_ttl_seconds: 300
    enable_audit: true
    redis_url: "redis://prod-redis:6379/0"

# Configurações de rollout
rollout_config:
  gradual_increase_days: 30
  percentage_step: 5.0
  max_percentage: 100.0
  min_percentage: 0.0

# Configurações de auditoria
audit_config:
  max_evaluations: 10000
  retention_days: 90
  export_format: "json"
  enable_alerts: true 