# 🔐 SECRETS MANAGEMENT - OMNİ KEYWORDS FINDER
# 📅 Criado: 2025-01-27
# 🔧 Tracing ID: CHECKLIST_99_PERCENT_20250127_001
# ⚠️ NUNCA commitar este arquivo no Git

# =============================================================================
# 🚨 CONFIGURAÇÃO DE SEGURANÇA CRÍTICA
# =============================================================================

secrets_management:
  provider: "hashicorp_vault"  # ou "aws_secrets_manager", "azure_key_vault"
  environment: "production"
  encryption_algorithm: "AES-256-GCM"
  key_rotation_interval: "30d"
  audit_logging: true

# =============================================================================
# 🔑 SECRETS PRINCIPAIS (VALORES EXEMPLO - SUBSTITUIR EM PRODUÇÃO)
# =============================================================================

database:
  postgresql:
    host: "localhost"
    port: 5432
    database: "omni_keywords_production"
    username: "omni_user"
    password: "omni_secure_password_2025_ultra_encrypted"
    ssl_mode: "require"
    connection_pool_size: 20
    max_connections: 100

  redis:
    host: "localhost"
    port: 6379
    password: "redis_secure_password_2025_ultra_encrypted"
    database: 0
    ssl: true

# =============================================================================
# 🔐 AUTENTICAÇÃO E AUTORIZAÇÃO
# =============================================================================

authentication:
  jwt:
    secret_key: "jwt_secret_key_omni_keywords_2025_production_ultra_secure_256_bits"
    algorithm: "HS256"
    access_token_expires: 3600
    refresh_token_expires: 604800
    issuer: "omni-keywords-finder"
    audience: "omni-keywords-users"

  oauth2:
    google:
      client_id: "your_google_client_id_here"
      client_secret: "your_google_client_secret_here"
      redirect_uri: "https://omni-keywords-finder.com/auth/google/callback"
      scopes: ["openid", "email", "profile"]

# =============================================================================
# 🌐 APIs EXTERNAS
# =============================================================================

external_apis:
  google:
    api_key: "your_google_api_key_here"
    search_console_api_key: "your_search_console_api_key_here"
    analytics_api_key: "your_analytics_api_key_here"
    maps_api_key: "your_maps_api_key_here"

  openai:
    api_key: "your_openai_api_key_here"
    organization: "your_openai_org_id_here"
    model: "gpt-4-turbo-preview"

  serpapi:
    api_key: "your_serpapi_key_here"

  ahrefs:
    api_key: "your_ahrefs_api_key_here"
    api_secret: "your_ahrefs_api_secret_here"

  semrush:
    api_key: "your_semrush_api_key_here"

# =============================================================================
# 📧 EMAIL E NOTIFICAÇÕES
# =============================================================================

email:
  smtp:
    host: "smtp.gmail.com"
    port: 587
    username: "notifications@omni-keywords-finder.com"
    password: "your_smtp_password_here"
    use_tls: true
    use_ssl: false

  notifications:
    from_email: "notifications@omni-keywords-finder.com"
    support_email: "support@omni-keywords-finder.com"
    admin_email: "admin@omni-keywords-finder.com"

# =============================================================================
# 🚨 ALERTAS E MONITORAMENTO
# =============================================================================

alerts:
  slack:
    webhook_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
    channel: "#omni-keywords-alerts"
    username: "Omni Keywords Bot"

  pagerduty:
    api_key: "your_pagerduty_api_key_here"
    service_id: "your_pagerduty_service_id_here"
    escalation_policy: "your_escalation_policy_id_here"

  email:
    critical_alerts: ["admin@omni-keywords-finder.com", "tech@omni-keywords-finder.com"]
    warning_alerts: ["support@omni-keywords-finder.com"]

# =============================================================================
# 🔒 SEGURANÇA AVANÇADA
# =============================================================================

security:
  encryption:
    master_key: "master_encryption_key_256_bits_ultra_secure"
    key_derivation_function: "PBKDF2"
    salt_length: 32
    iterations: 100000

  waf:
    secret_key: "waf_secret_key_2025_ultra_secure"
    rules_file: "/etc/waf/rules.conf"
    block_suspicious_ips: true

  rate_limiting:
    secret_key: "rate_limit_secret_key_2025_ultra_secure"
    redis_prefix: "rate_limit:"

# =============================================================================
# 📊 ANALYTICS E TRACKING
# =============================================================================

analytics:
  google_analytics:
    tracking_id: "GA-XXXXXXXXX-X"
    measurement_protocol_secret: "your_ga_measurement_protocol_secret"

  mixpanel:
    token: "your_mixpanel_token_here"
    project_id: "your_mixpanel_project_id"

  hotjar:
    site_id: "your_hotjar_site_id"
    secret_key: "your_hotjar_secret_key"

# =============================================================================
# 🔄 BACKUP E RECOVERY
# =============================================================================

backup:
  aws:
    access_key_id: "your_aws_access_key_id"
    secret_access_key: "your_aws_secret_access_key"
    region: "us-east-1"
    s3_bucket: "omni-keywords-backups"
    kms_key_id: "your_kms_key_id"

  encryption:
    backup_encryption_key: "backup_encryption_key_256_bits_ultra_secure"
    algorithm: "AES-256-GCM"

# =============================================================================
# 🚀 DEPLOY E INFRAESTRUTURA
# =============================================================================

deployment:
  docker:
    registry_url: "registry.omni-keywords-finder.com"
    registry_username: "your_registry_username"
    registry_password: "your_registry_password"

  kubernetes:
    cluster_name: "omni-keywords-cluster"
    namespace: "omni-keywords-production"
    service_account_token: "your_service_account_token"

  terraform:
    state_bucket: "omni-keywords-terraform-state"
    state_key: "production/terraform.tfstate"
    region: "us-east-1"

# =============================================================================
# 🔍 MONITORAMENTO E OBSERVABILIDADE
# =============================================================================

monitoring:
  prometheus:
    auth_token: "your_prometheus_auth_token"
    remote_write_url: "https://prometheus.omni-keywords-finder.com/api/v1/write"

  grafana:
    admin_password: "your_grafana_admin_password"
    api_key: "your_grafana_api_key"

  jaeger:
    auth_token: "your_jaeger_auth_token"
    collector_endpoint: "https://jaeger.omni-keywords-finder.com:14268/api/traces"

# =============================================================================
# 🎯 CONFIGURAÇÕES ESPECÍFICAS DO SISTEMA
# =============================================================================

system:
  keywords_finder:
    api_rate_limit_key: "keywords_finder_rate_limit_secret_2025"
    analysis_queue_secret: "analysis_queue_secret_2025"
    cache_invalidation_key: "cache_invalidation_secret_2025"

  processing:
    worker_secret: "worker_secret_2025_ultra_secure"
    queue_encryption_key: "queue_encryption_key_256_bits"

# =============================================================================
# 🔧 CONFIGURAÇÕES DE DESENVOLVIMENTO (NÃO USAR EM PRODUÇÃO)
# =============================================================================

development:
  debug_mode: false
  test_api_keys: false
  mock_external_services: false

# =============================================================================
# 📝 VALIDAÇÃO E AUDITORIA
# =============================================================================

validation:
  secret_strength_check: true
  key_rotation_reminder: true
  access_logging: true
  audit_trail: true

audit:
  log_secret_access: true
  track_secret_usage: true
  alert_on_unauthorized_access: true
  periodic_secret_scan: true

# =============================================================================
# 🚨 PROCEDIMENTOS DE EMERGÊNCIA
# =============================================================================

emergency:
  secret_rotation_procedure:
    - "1. Gerar novas chaves usando: openssl rand -hex 32"
    - "2. Atualizar secrets no Vault/AWS Secrets Manager"
    - "3. Reiniciar serviços para aplicar novas chaves"
    - "4. Verificar logs por erros de autenticação"
    - "5. Monitorar métricas de erro por 24h"

  incident_response:
    - "1. Isolar sistema comprometido"
    - "2. Rotacionar todas as chaves imediatamente"
    - "3. Analisar logs de acesso"
    - "4. Notificar equipe de segurança"
    - "5. Documentar incidente"

# =============================================================================
# 📋 CHECKLIST DE SEGURANÇA
# =============================================================================

security_checklist:
  - "✅ Todas as chaves têm pelo menos 256 bits"
  - "✅ Chaves são rotacionadas a cada 30 dias"
  - "✅ Acesso aos secrets é logado"
  - "✅ Secrets não aparecem em logs"
  - "✅ Backup dos secrets é criptografado"
  - "✅ Acesso aos secrets é restrito por IP"
  - "✅ MFA habilitado para acesso aos secrets"
  - "✅ Auditoria regular dos acessos"
  - "✅ Procedimento de emergência documentado"
  - "✅ Equipe treinada em segurança de secrets"

# =============================================================================
# ⚠️ AVISOS IMPORTANTES
# =============================================================================

warnings:
  - "NUNCA commitar este arquivo no Git"
  - "Usar variáveis de ambiente em produção"
  - "Rotacionar chaves regularmente"
  - "Monitorar logs por vazamento de secrets"
  - "Usar secrets management enterprise (Vault, AWS Secrets Manager)"
  - "Implementar MFA para acesso aos secrets"
  - "Fazer backup seguro dos secrets"
  - "Documentar procedimentos de emergência"
  - "Treinar equipe em segurança de secrets"
  - "Auditar acesso aos secrets regularmente" 