# Service Level Objectives (SLOs) Configuration
# Criado em: 2025-01-27
# Tracing ID: COMPLETUDE_CHECKLIST_20250127_001

# Configuração global de SLOs
global:
  evaluation_window: "30d"  # Janela de avaliação
  alerting_window: "5m"     # Janela para alertas
  error_budget: 0.01        # 1% de orçamento de erro
  compliance_threshold: 0.99 # 99% de compliance

# SLOs por serviço
services:
  api_gateway:
    name: "API Gateway"
    description: "Gateway principal da API"
    slos:
      - name: "availability"
        description: "Disponibilidade do serviço"
        target: 0.9999  # 99.99%
        measurement: "uptime"
        window: "30d"
        alert_threshold: 0.999  # 99.9%
        
      - name: "response_time"
        description: "Tempo de resposta p95"
        target: 0.200   # 200ms
        measurement: "latency_p95"
        window: "5m"
        alert_threshold: 0.500  # 500ms
        
      - name: "error_rate"
        description: "Taxa de erro HTTP 5xx"
        target: 0.001   # 0.1%
        measurement: "error_rate_5xx"
        window: "5m"
        alert_threshold: 0.005  # 0.5%

  keyword_analyzer:
    name: "Keyword Analyzer Service"
    description: "Serviço de análise de keywords"
    slos:
      - name: "availability"
        description: "Disponibilidade do serviço"
        target: 0.9995  # 99.95%
        measurement: "uptime"
        window: "30d"
        alert_threshold: 0.999  # 99.9%
        
      - name: "analysis_latency"
        description: "Latência de análise p95"
        target: 1.0     # 1 segundo
        measurement: "analysis_latency_p95"
        window: "5m"
        alert_threshold: 2.0    # 2 segundos
        
      - name: "accuracy"
        description: "Precisão da análise"
        target: 0.95    # 95%
        measurement: "analysis_accuracy"
        window: "1h"
        alert_threshold: 0.90   # 90%

  database:
    name: "Database Service"
    description: "Serviço de banco de dados"
    slos:
      - name: "availability"
        description: "Disponibilidade do banco"
        target: 0.9999  # 99.99%
        measurement: "database_uptime"
        window: "30d"
        alert_threshold: 0.9995 # 99.95%
        
      - name: "query_latency"
        description: "Latência de queries p95"
        target: 0.100   # 100ms
        measurement: "query_latency_p95"
        window: "5m"
        alert_threshold: 0.300  # 300ms
        
      - name: "connection_pool"
        description: "Disponibilidade de conexões"
        target: 0.999   # 99.9%
        measurement: "connection_pool_availability"
        window: "5m"
        alert_threshold: 0.99   # 99%

  cache_service:
    name: "Cache Service"
    description: "Serviço de cache"
    slos:
      - name: "availability"
        description: "Disponibilidade do cache"
        target: 0.9995  # 99.95%
        measurement: "cache_uptime"
        window: "30d"
        alert_threshold: 0.999  # 99.9%
        
      - name: "hit_rate"
        description: "Taxa de hit do cache"
        target: 0.80    # 80%
        measurement: "cache_hit_rate"
        window: "5m"
        alert_threshold: 0.70   # 70%
        
      - name: "response_time"
        description: "Tempo de resposta p95"
        target: 0.010   # 10ms
        measurement: "cache_latency_p95"
        window: "5m"
        alert_threshold: 0.050  # 50ms

  authentication:
    name: "Authentication Service"
    description: "Serviço de autenticação"
    slos:
      - name: "availability"
        description: "Disponibilidade do serviço"
        target: 0.9999  # 99.99%
        measurement: "auth_uptime"
        window: "30d"
        alert_threshold: 0.9995 # 99.95%
        
      - name: "login_latency"
        description: "Latência de login p95"
        target: 0.500   # 500ms
        measurement: "login_latency_p95"
        window: "5m"
        alert_threshold: 1.0    # 1 segundo
        
      - name: "security_incidents"
        description: "Incidentes de segurança"
        target: 0.0     # 0 incidentes
        measurement: "security_incidents_count"
        window: "30d"
        alert_threshold: 1      # 1 incidente

# SLOs de infraestrutura
infrastructure:
  load_balancer:
    name: "Load Balancer"
    description: "Balanceador de carga"
    slos:
      - name: "availability"
        description: "Disponibilidade do LB"
        target: 0.9999  # 99.99%
        measurement: "lb_uptime"
        window: "30d"
        alert_threshold: 0.9995 # 99.95%
        
      - name: "health_check"
        description: "Health checks bem-sucedidos"
        target: 0.999   # 99.9%
        measurement: "health_check_success_rate"
        window: "5m"
        alert_threshold: 0.99   # 99%

  monitoring:
    name: "Monitoring System"
    description: "Sistema de monitoramento"
    slos:
      - name: "availability"
        description: "Disponibilidade do monitoring"
        target: 0.9995  # 99.95%
        measurement: "monitoring_uptime"
        window: "30d"
        alert_threshold: 0.999  # 99.9%
        
      - name: "alert_delivery"
        description: "Entrega de alertas"
        target: 0.999   # 99.9%
        measurement: "alert_delivery_rate"
        window: "5m"
        alert_threshold: 0.99   # 99%

# SLOs de negócio
business:
  user_experience:
    name: "User Experience"
    description: "Experiência do usuário"
    slos:
      - name: "page_load_time"
        description: "Tempo de carregamento de página"
        target: 2.0     # 2 segundos
        measurement: "page_load_time_p95"
        window: "5m"
        alert_threshold: 3.0    # 3 segundos
        
      - name: "search_response_time"
        description: "Tempo de resposta da busca"
        target: 1.0     # 1 segundo
        measurement: "search_latency_p95"
        window: "5m"
        alert_threshold: 2.0    # 2 segundos
        
      - name: "user_satisfaction"
        description: "Satisfação do usuário"
        target: 4.5     # 4.5/5.0
        measurement: "user_satisfaction_score"
        window: "7d"
        alert_threshold: 4.0    # 4.0/5.0

  data_quality:
    name: "Data Quality"
    description: "Qualidade dos dados"
    slos:
      - name: "data_accuracy"
        description: "Precisão dos dados"
        target: 0.98    # 98%
        measurement: "data_accuracy_rate"
        window: "1h"
        alert_threshold: 0.95   # 95%
        
      - name: "data_freshness"
        description: "Atualidade dos dados"
        target: 300     # 5 minutos
        measurement: "data_freshness_seconds"
        window: "5m"
        alert_threshold: 600    # 10 minutos

# Configurações de alerta
alerting:
  channels:
    - name: "critical"
      type: "pagerduty"
      escalation_policy: "critical"
      conditions:
        - slo_violation: true
        - error_budget_burn_rate: "> 10x"
        
    - name: "warning"
      type: "slack"
      channel: "#alerts"
      conditions:
        - slo_violation: true
        - error_budget_burn_rate: "> 2x"
        
    - name: "info"
      type: "email"
      recipients: ["team@company.com"]
      conditions:
        - slo_violation: true

  escalation:
    levels:
      - level: 1
        timeout: "5m"
        notify: ["oncall"]
      - level: 2
        timeout: "15m"
        notify: ["team-lead"]
      - level: 3
        timeout: "30m"
        notify: ["manager"]

# Configurações de métricas
metrics:
  collection_interval: "30s"
  retention_period: "90d"
  aggregation_rules:
    - name: "slo_calculation"
      query: |
        sum(rate(http_requests_total{status=~"5.."}[5m])) 
        / 
        sum(rate(http_requests_total[5m]))
      window: "5m"
      
    - name: "latency_p95"
      query: |
        histogram_quantile(0.95, 
          sum(rate(http_request_duration_seconds_bucket[5m])) by (le)
        )
      window: "5m"

# Configurações de compliance
compliance:
  reporting:
    frequency: "weekly"
    format: ["json", "html", "pdf"]
    recipients: ["compliance@company.com"]
    
  audit:
    enabled: true
    retention: "7y"
    encryption: true
    
  certifications:
    - name: "SOC2"
      requirements:
        - availability: "99.9%"
        - security_incidents: "0"
    - name: "ISO27001"
      requirements:
        - data_protection: "100%"
        - access_control: "100%"

# Configurações de backup e recuperação
recovery:
  rto: "15m"  # Recovery Time Objective
  rpo: "5m"   # Recovery Point Objective
  
  procedures:
    - name: "database_restore"
      estimated_time: "10m"
      dependencies: ["backup_verification"]
      
    - name: "service_restart"
      estimated_time: "2m"
      dependencies: ["health_check"]
      
    - name: "cache_warmup"
      estimated_time: "5m"
      dependencies: ["service_restart"]

# Configurações de teste de SLOs
testing:
  synthetic_monitoring:
    enabled: true
    frequency: "1m"
    endpoints:
      - "/health"
      - "/api/v1/keywords"
      - "/api/v1/analysis"
      
  chaos_engineering:
    enabled: true
    experiments:
      - name: "network_latency"
        frequency: "weekly"
        duration: "5m"
        max_latency: "500ms"
        
      - name: "service_failure"
        frequency: "monthly"
        duration: "2m"
        max_downtime: "1m"

# Configurações de documentação
documentation:
  auto_generate: true
  format: "markdown"
  location: "docs/slos/"
  include:
    - "slo_definitions"
    - "alerting_rules"
    - "recovery_procedures"
    - "compliance_reports" 